---
title: "p8105_hw5_dz2426"
author: "Duzhi Zhao"
date: "11/2/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8, 
  fig.height = 6,
  out.width = "100%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  # Clean variable names
  janitor::clean_names()
```

```{r}
# Create vector argument x 
x = vector("list", length = 5)

# Create a function "q1_f"
q1_f = function(x) {
  # If input is numeric, replace value with the mean of this column
  if (is.numeric(x)) {
    replace(x, is.na(x), mean(x, na.rm = TRUE))
  } 
  # If input is not numeric, replace value with "virginica"
  else if (!is.numeric(x)) {
    replace(x, is.na(x), "virginica")
  }
}

# Apply q1_f function to each column of dataset
x = map(iris_with_missing, q1_f)

# Updated iris dataset
iris_without_missing = tibble(
  sepal_length = round(x$sepal_length, digits = 1),
  sepal_width = round(x$sepal_width, digits = 1),
  petal_length = round(x$petal_length, digits = 1),
  petal_width = round(x$sepal_width, digits = 1),
  species = x$species
) %>% 
  # Show the first 22 rows which indicate the success of filling NA
  head(22)

knitr::kable(iris_without_missing, caption = "Table 1: First 22 rows of Iris dataset")

```

# Problem 2
```{r}
# Create a dataframe first including all file names
q2_df = tibble(
  file_names = list.files(path = './data/')
) %>% 
  # Read in data using map function
  mutate(name = map(.x = str_c("./data/", file_names), 
                    ~read_csv(.x))) %>% 
  # Expand dataset completely
  unnest() %>% 
  # Separate variable "file_names" into two variables "group" and "subject id"
  separate(file_names, into = c("group", "subject_id"), sep = "_", remove = F) %>% 
  # Tidy weekly observation data in a pivot_longer format
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "observation") %>% 
  # Tidy data
  mutate(week = str_replace(week, "week_", ""),
         file_names = str_replace(file_names, ".csv", ""),
         subject_id = str_replace(subject_id, ".csv", ""),
         group = str_replace(group, "con", "control"),
         group = str_replace(group, "exp", "experimental")
  )
```

```{r}
# Spaghetti plot
q2_df %>% 
  ggplot(aes(x = week, y = observation, group = subject_id, color = subject_id)) +
  geom_line() + 
  facet_grid(~group) +
  labs(x = "Week", 
       y = "Observation",
       title = "Observations on each subject over time",
       fill = "Subject ID"
    ) +
  theme(strip.text = element_text(size = 12, face = 'bold'))
```

**Comments:**  
The spaghetti plot shows larger values for subjects in experimental group compared to those in control group. Furthermore, observations on experimental subjects indicated a positive trend over time, while subjects in control group did not show significant difference after 8 weeks.

# Problem 3
```{r}
# Create linear model regression function
sim_regression = function(n, beta0 = 2, beta1) {
  
  sim_data = tibble(
    x_i1 = rnorm(n, mean = 0, sd = 1),
    y_i = beta0 + beta1 * x_i1 + rnorm(n, 0, sqrt(50)) # standard error term~N[0, sqrt50]
  )
  
  ls_fit = lm(y_i ~ x_i1, data = sim_data)
  broom::tidy(ls_fit)
}

# Set beta1 = 0, and generate 10000 datasets from the model
lm_rerun = rerun(10000, sim_regression(n = 30, beta1 = 0)) %>% 
  bind_rows() %>% 
  janitor::clean_names() %>% 
  # select correct p_value
  filter(term == "x_i1") %>% 
  select(estimate, p_value)
```

```{r}

output = vector("list", length = 7)
for (i in 1:7) {
  output[[i]] = rerun(30, sim_regression(30, 2, beta1 = i - 1))
}

sim_results = bind_rows(output)
```

```{r}
sim_results
```

